### ISSUE TITLE
Tinker Construct Mattocks

### ISSUE THREAD

**Issue by jadedcat** [Vanhal/ProgressiveAutomation#101]
Tinkers Construct Mattocks do not appear to work in the farm. Which is an issue in packs that disable hoes or make hoes have very little durability.

**Comment by Vanhal** [comment]
You know I was sure I added that before. Added now anyway! Just to note (which you probably already know) that you'll need at least a stone planter to be able to use a flint version of the tools, you might be better just disabling the wooden version completely since you can't make wooden tools. (Unless you've changed around the level of flint??)
