### ISSUE TITLE
Progressive Automation feeding into chests incorrectly.

### ISSUE THREAD

**Issue by Frictor** [Vanhal/ProgressiveAutomation#120]
Unless using hoppers or other tools, I have noticed that the PA devices, of Diamond rating, feed into only the lower half of double chest storage.  This is similar to how hoppers fed in, when originally added to Minecraft.  Have not double-checked other grades of PA devices.  Using version 1.6.4 for MC 1.8

**Comment by Badcholo** [comment]
I use Applied energistics to run this properly. Everything mined goes into the system from the top slot. Cobblestone, pickaxe, shovels go in to the miner from the back, Power comes in from the right side. There is no looping of items or lack of space. I'll try to make more simple setups with other mods. This works for me very well. I have also installed Steel industries mod since i get steel and titanium that the miner mines and can be reused for the tools. There is no other use for titanium other than for tools so it works great with this mod!
![2015-04-19_01 45 44](https://cloud.githubusercontent.com/assets/10932905/7218817/1f3636bc-e636-11e4-8d73-9bbf1119c910.png)

**Comment by twothe** [comment]
If you want I have a function I use in my own mods that you can use to add items stacks to a container in a propper way: mergeItemStack in https://github.com/twothe/twotility/blob/master/src/main/java/two/twotility/container/ContainerBase.java

You can find examples in the same directory.

**Comment by Vanhal** [comment]
Should be fixed in the newest 1.8.9 version
