### ISSUE TITLE
Miner optionally does not fill mined area with cobblestone

### ISSUE THREAD

**Issue by yoiang** [Vanhal/ProgressiveAutomation#215]
I appreciate the mod, super helpful! It would be nice to either have a server side option or an upgrade that leaves the mined areas empty rather than filling them with cobblestone as is the current behavior.

**Comment by Vanhal** [comment]
No sorry, replacing with cobble is part of the balance, it will not be changed.

**Comment by yoiang** [comment]
@Vanhal k! What do you mean by the balance?

**Comment by Bonesy1** [comment]
I get that it's part of the balance but at the very least allow the player the option to choose how they want to use the mod. I downloaded this to stop spending time in minecraft hoarding cobble and wasting time, resources and pickaxes clearing areas by hand, and now in order to keep up with the demand for cobble, I need to hoard cobble to supply the miner, or get a cobble gen upgrade, which requires a lot of work to get to that stage, a lot of that work requiring mining more and more cobble by hand taking time instead of letting me choose to simply automatically mine the area. 

At least give the choice for people, should they want. There's already the option to increase most things to OP in the config.
