### ISSUE TITLE
Hi, version 1.12.2

### ISSUE THREAD

**Issue by angelshurikan** [Vanhal/ProgressiveAutomation#360]
My name is Angeliu'S Shurikan.
I'm gonna try, update mod in 1.12.2.

**Comment by Hubber116sx** [comment]
How's your progress on this doing?

**Comment by sweetkid169** [comment]
I attempted to follow https://www.reddit.com/r/feedthebeast/comments/8mf1ht/technical_how_to_manually_update_a_mod_commit/
but I don't think it would have worked... though not sure... Would love to see this updated.

**Comment by Psycho-Ray** [comment]
I was almost done, then college happened. Anyway, I'm going on vacation this friday, and I've just bought a new computer, so I'm excited to play minecraft again, among other games. It's a Ryzen 2400g with no dedicated GPU, but it should perform deliciously well on minecraft, without me feeling like I'm wasting money with something much better than necessary xD

Anyway, IF I start playing minecraft again, this mod will be available for 1.12. That's a promise.

**Comment by sweetkid169** [comment]
You are a glorious individual. I do hope your able to do that. Keep us in the loop. Thanks.

**Comment by Psycho-Ray** [comment]
I'm down to 17 errors and 63 warnings. From hundreds.

Plus, some features related to recipes are currently missing, which means I'll have to release a beta first

**Comment by Psycho-Ray** [comment]
![image](https://user-images.githubusercontent.com/26625054/50179462-3c616a80-02ee-11e9-8080-1a64467b0f54.png)
Soon(tm)

**Comment by dshadowwolf** [comment]
See #362 👍

**Comment by zymex22** [comment]
any news on this? really wanna play PA on 1.12 cant find any dl links to it, if anyone have made a port yet

**Comment by Psycho-Ray** [comment]
I have messaged @Vanhal  on his tweeter a long time ago saying I had a 1.12 version, but he never replied ;-;

@zymex22 
You can play with my unofficial release here:
https://github.com/Psycho-Ray/ProgressiveAutomation/blob/master/ProgressiveAutomation-1.12.2-1.7.7.jar

Just click download, and play it on minecraft. What I do know is that it might be a pain to merge my version into @dshadowwolf version to use all the fixes from both, because I fixed a lot of things too =X

**Comment by zymex22** [comment]
@dshadowwolf are your version ready / released yet?
saw you posted a pull request.

**Comment by Psycho-Ray** [comment]
@zymex22 I mean to say I didn't know if I have compiled correctly. This version I uploaded is fully functional, and I have been playing with it for a few months.

I'm not sure what to do about @dshadowwolf version, tho. I did the 1.11, and now the 1.12 too, so I'm familiar with the code. It's not too hard to learn it tho, so I'm sure he did a good job. It's probably easier to just choose one, but it would be better to try and merge both.

What say you, @dshadowwolf?

**Comment by zymex22** [comment]
@Psycho-Ray @Psycho-Ray cant run yours version didnt set my self too much in it :D
PB of crash report here: https://pastebin.com/jzmc8PTe i run a modified version of 1.12 FTB ultimate reloaded =)

**Comment by dshadowwolf** [comment]
The license that has covered PA since February 2015 (a variation of the TeamCoFH "Don't Be a Jerk" license) makes it so that I cannot, legally, release the fork that I have PR'd.

I have begun work (along with some other members of the MMD team) on a "spiritual successor", but this work means getting our support library (which currently lives inside BaseMetals) released in a fully standalone state.

Other than that... The PR I opened contains a fully functional port that removes any use of or dependence on RF in favor of the built-into-forge "Forge Energy" system. I'd offer downloads, but again, the license is rather clear that this is more of a "visible source" situation than a classic "open source" siutation - meaning I cannot fork and release.

See the license - ``This mod cannot be distributed on its own from any source unless given explicit permission.`` - at [line 65 of the license](https://github.com/Vanhal/ProgressiveAutomation/blob/5a75e555ca404701eb130d6a5b03e185468209de/LICENSE#L65). This means that, as Vanhal appears to be completely incommunicado, no fork or forward port can be distributed, as he is not responding to any requests for permission.

**Comment by zymex22** [comment]
thats sucks with all work done, and no way to release it =( 
thats a really nice early on mod, that really easy to get into without too much effort to learn it like industrial foregoing and such

**Comment by zymex22** [comment]
thats sucks with all work done, and no way to release it =( 
thats a really nice early on mod, that really easy to get into without too much effort to learn it like industrial foregoing and such

@dshadowwolf i send you a pm on curseforge i have a question about the mod

**Comment by Psycho-Ray** [comment]
@dshadowwolf Oh well, should have read those things. Shame on me. By the way, could you elaborate a bit on your decision of not supporting RF anymore?

**Comment by Psycho-Ray** [comment]
@zymex22 how can I PM you? Maybe I can assist you somehow other than sending you the version I was using (why did I go through all the trouble of building a new one anyway? derp)

**Comment by dshadowwolf** [comment]
It supports RF in that RF actually does an FE interface internally, but... its actually that the mod is now "self contained" in its code-base - all it needs is Forge and it can be built. No need for any other mod to provide the power system.

**Comment by zymex22** [comment]
@Psycho-Ray i have send you an email

**Comment by Vanhal** [comment]
I'm still here. I've had the PR email in my inbox to remind me to pull it and compile it.
I have some time over the weekend to have a look into this and get it going.

**Comment by zymex22** [comment]
@Vanhal thank you! :D nice to see you back! :D

and thanks to @Psycho-Ray and @dshadowwolf for your work :D

**Comment by dshadowwolf** [comment]
@Vanhal has accepted PR #362 and the build is now available on CurseForge. This issue can be closed.
