### ISSUE TITLE
Suggesting Other metal version of machines

### ISSUE THREAD

**Issue by InkDragon** [Vanhal/ProgressiveAutomation#96]
Suggesting support for other metals(such as copper) added by mods to be useable in the creation of machines.

Mostly looking for support for the common metals like those found in thermal foundation to be used to create alternate versions of the machines. Either with the same power as the iron versions or as an alternative progression system.

**Comment by medsal15** [comment]
List of metals I know (not every metals): Tin, Enderium, Blazium (Gany's Nether), Endium (Gany's End), Bronze, Gold, Platinium, Mithril, Adamantium, Lumium. If you want more of these metals tell me.

**Comment by InkDragon** [comment]
I was thinking more along the lines of Bronze, Copper, Steel, and possibly silver or aluminum. Basically just the ones that are in some of the most common mods, like Tinker's Construct and Thermal Expansion/TeamCoFH's mods. That way they could be built with any oredictionary compatible version of of the ingot

**Comment by liftoff** [comment]
Considering that PA uses Thermal Expansion's RF for power it only makes sense to also support Thermal Expansion's metals.  I don't care so much about having, say, a copper miner as much as I would like to be able to use a copper pickaxe in an iron miner (since copper is of a lesser level).  Bronze tools in an iron miner would also make sense and diamond miners shouldn't have restrictions.

**Comment by TANGOjPANDA** [comment]
I would say if you use a specific metal you would get a specific trait. For instance shiny/platinum ingots are fairly rare so this would upgrade the top teir (diamond level )of the mining machine with fortune. This can be applied in a crafting grid. Maybe every 8 ingots adds a layer of fortune. The upgrade would be metal specific Or metals specific.

**Comment by Badcholo** [comment]
I use Steel Industries mod. It adds Steel and Titanium. Titanium is only used to craft tools, so i use that for the miner since it produces more than enough to keep using it. I like the idea of adding such a ore to  this mod for the same purpose. Titanium can only be smelted and it's durability makes it so that it produces a little more than what is used. I like this method since i don't like using the minerals i mine to refill the machine. i like to see profit and this machine is currently lacking in such.
note i also use the extra titanium to make axes and hoes.
